require "swiss_admin/cli/host_cli"
require "swiss_admin/cli/hardware_cli"
require "swiss_admin/cli/network_cli"
require "swiss_admin/cli/user_cli"
require "swiss_admin/cli/web_cli"
require "swiss_admin/cli/cli"
